// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGw_kCRDqiEa_LI_mAyikwV9HftGYUB30',
    appId: '1:953182524873:web:286215aec630cecef0c418',
    messagingSenderId: '953182524873',
    projectId: 'explorego-d5f85',
    authDomain: 'explorego-d5f85.firebaseapp.com',
    databaseURL: 'https://explorego-d5f85-default-rtdb.firebaseio.com',
    storageBucket: 'explorego-d5f85.appspot.com',
    measurementId: 'G-EGX4FD48G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAEw_26tCeRGVy6TA7f6eJCfMTonH3qWI',
    appId: '1:953182524873:android:ba5e4e8a3be65decf0c418',
    messagingSenderId: '953182524873',
    projectId: 'explorego-d5f85',
    databaseURL: 'https://explorego-d5f85-default-rtdb.firebaseio.com',
    storageBucket: 'explorego-d5f85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuimAytYD4lEdsVcWSJ-eyXEligZrrpQ',
    appId: '1:953182524873:ios:a7d3d69886877254f0c418',
    messagingSenderId: '953182524873',
    projectId: 'explorego-d5f85',
    databaseURL: 'https://explorego-d5f85-default-rtdb.firebaseio.com',
    storageBucket: 'explorego-d5f85.appspot.com',
    iosClientId: '953182524873-89iaa3f06e8h1fochmpga9q1kbqgbq2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.explorego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNuimAytYD4lEdsVcWSJ-eyXEligZrrpQ',
    appId: '1:953182524873:ios:a7d3d69886877254f0c418',
    messagingSenderId: '953182524873',
    projectId: 'explorego-d5f85',
    databaseURL: 'https://explorego-d5f85-default-rtdb.firebaseio.com',
    storageBucket: 'explorego-d5f85.appspot.com',
    iosClientId: '953182524873-89iaa3f06e8h1fochmpga9q1kbqgbq2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.explorego',
  );
}
